Repository masters2023-2nd-project-03/second-hand, pull requests merged in 2023-06, with the labels that each got.

#2 CHORE: FE 프로젝트 초기 세팅 구성을 했습니다
  frontend/.eslintignore
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.prettierrc
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/tsconfig.json
Labels: FE, SETTING

#5 CHORE: 라이브러리 설치 (#3)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/styles/GlobalStyles.tsx
Labels: FE, SETTING

#9 CHORE: FE 릴리즈 세팅 (#8)
  .github/workflows/auto-deploy.yml
  Dockerfile
  conf/nginx/nginx.conf
Labels: FE, SETTING

#21 FEAT: API 연동을 위한 프로토타입 제작하였습니다
  frontend/src/components/App/index.tsx
Labels: FE, FEAT

#26 FIX: 배포 코드 수정, Git 배포 이슈 해결(#25)
  .github/workflows/auto-deploy.yml
  .gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/second-hand.iml
  .idea/modules/second-hand.main.iml
  .idea/modules/second-hand.test.iml
  Dockerfile
  backend/build.gradle
  backend/src/main/java/team03/secondhand/configure/WebConfigure.java
  backend/src/main/resources/application.properties
Labels: BE, EDIT, SETTING

#49 FEAT: NavBarHome 컴포넌트 구현 (#41)
  frontend/src/assets/icons/index.tsx
  frontend/src/assets/icons/label.svg
  frontend/src/components/App/index.tsx
  frontend/src/components/Dropdown/DropdownPanel/styles.ts
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/Dropdown/styles.ts
  frontend/src/components/NavBarHome/index.tsx
  frontend/src/components/NavBarHome/styles.ts
  frontend/src/components/StatusBar/index.tsx
Labels: FE, FEAT

#51 FEAT: TabBar 컴포넌트 구현 했습니다 (#42)
  frontend/src/components/TabBar/index.tsx
  frontend/src/components/TabBar/styles.ts
  frontend/src/index.tsx
Labels: FE, FEAT

#68 FEAT: 로그인 관련 흐름을 구성하였습니다
  frontend/src/api/login.tsx
  frontend/src/components/AccountPage/index.tsx
  frontend/src/components/App/index.tsx
  frontend/src/components/Button/index.tsx
  frontend/src/components/Button/styles.ts
  frontend/src/components/Callback/index.tsx
  frontend/src/components/ProtectedRoute/index.tsx
  frontend/src/constants/api.ts
  frontend/src/constants/login.ts
  frontend/src/constants/routeUrl.ts
  frontend/src/context/Auth.tsx
  frontend/src/hooks/useAsync.ts
  frontend/src/pages/Account/index.tsx
  frontend/src/pages/Login/index.tsx
  frontend/tsconfig.json
Labels: FE, FEAT

#81 FEAT: API 함수를 구현했습나다
  frontend/.gitignore
  frontend/src/api/axios.ts
  frontend/src/api/category.ts
  frontend/src/api/location.ts
  frontend/src/api/login.ts
  frontend/src/api/product.ts
  frontend/src/components/App/index.tsx
  frontend/src/hooks/useAsync.ts
  frontend/src/index.tsx
Labels: FE, FEAT

#87 FEAT: 회원가입 화면에서 이미지를 선택하는 기능을 구현하였습니다
  iOS/Second-Hand/Second-Hand/UI/Account/ViewController/SignUpViewController.swift
  iOS/Second-Hand/Second-Hand/UI/Common/ViewController/SecondHandTabBarController.swift
Labels: iOS, FEAT

#103 EDIT: 사진 등록 후 홈 화면으로 이동 추가
  frontend/src/pages/SalesItem/index.tsx
Labels: FE, EDIT

#126 FEAT: 유저 정보 가져오기 기능을 구현하였습니다 #109
  frontend/src/api/axios.ts
  frontend/src/api/member.ts
  frontend/src/components/App/index.tsx
  frontend/src/components/Callback/index.tsx
  frontend/src/context/Auth.tsx
  frontend/src/pages/Account/index.tsx
  frontend/src/pages/Account/styles.ts
  frontend/src/pages/Login/index.tsx
  frontend/src/pages/Register/index.tsx
Labels: FE
